# Generated by Django 4.2.4 on 2023-10-06 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_home', models.CharField(db_index=True, max_length=50)),
                ('children', models.ManyToManyField(blank=True, related_name='parents', to='application.node')),
                ('parent', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='application.node')),
            ],
        ),
    ]
